## 爱快管理页面的 URL，结尾不要加 "/"，
## 如果在爱快自带 docker 运行，网关就是爱快地址，可以不写  如不填写，则使用第一个接口的网关地址作为爱快地址，
ikuai-url: http://10.1.1.1 # 爱快网页控制台登陆地址
username: admin # 爱快用户名
password: admin888  # 爱快密码
cron: 0 7 * * * # 执行更新的周期 格式为 crontab
AddErrRetryWait: 10s # 自动重试时间间隔 时间格式为 10s  120s
AddWait: 1s # 添加规则后等待时间 等待爱快释放性能
custom-isp:     # 自定义运营商  IP分流
  - name: 国内IP列表  # 自定义运营商名称
    ## 自定义运营商 cidr 列表网址，每行一个，超过5000行会自动分为多个，ipv6 地址会被删除 
    ## 下面演示规则使用了ghproxy.com的代理，如果失效请自行更换或另外想办法
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
    tag: ipcn # 规则的备注标签后缀 如果留空默认为自定义运营商名称
  - name: telegram
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
    tag: iptg
  - name: google
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
    tag: ipgoogle
  #- name: facebook
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/facebook.txt
  #  tag: ipfb
  #- name: twitter
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/twitter.txt
  #  tag: iptw
  #- name: cloudflare
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cloudflare.txt
  #  tag: ipcf
  #- name: netflix
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/netflix.txt
  #  tag: ipnf
  
stream-domain:      # 域名分流
  #- interface: wan2 # 分流线路
  #  src-addr: 10.1.1.2-10.1.1.254    # 分流的源地址 多ip段用“,”分开 参考 https://github.com/joyanhui/ikuai-bypass/issues/1#issuecomment-1892763993
  #  ## 域名列表网址，每行一个，超过1000行会自动分为多个
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt
  # 下面是强制走wan2的
  - interface: wan2
    src-addr: 10.1.1.2-10.1.1.254
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
    tag: gfw
  # 下面是自动走wan1直连的，网址列表较大，不建议启用,有可能会影响上网体验。
  #- interface: wan1
  #  src-addr: 10.1.1.2-10.1.1.254
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
  #  tag: cn
  #- interface: wan1
  #  src-addr: 10.1.1.2-10.1.1.254 
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt
  #  tag: apple
  #  下面是去广告的
  #  todo 以后会使用爱快的域名黑名单模式来实现广告过滤，暂时用线路分流功能屏蔽
  #  wan99是一个不可用或者不通的线路。因为网址列表较大，如爱快性能不佳不建议启用，建议使用另外部署的adguard mosdns等实现。
  #- interface: wan99
  #  src-addr: 10.1.1.2-10.1.1.254 
  #  url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
  #  tag: adFilter
