## 爱快管理页面的 URL，结尾不要加 "/"，
## 如不填写，则使用第一个接口的网关地址作为爱快地址，
## 如果在爱快自带 docker 运行，网关就是爱快地址，可以不写
ikuai-url: http://10.1.1.1
username: admin # 爱快用户名
password: admin888  # 爱快密码
cron: 0 4 * * * # 执行更新的周期 crontab
custom-isp:     # 自定义运营商  IP分流
  - name: 国内IP列表  # 自定义运营商名称
    ## 自定义运营商 cidr 列表网址，每行一个，超过5000行会自动分为多个，ipv6 地址会被删除 
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
  - name: telegram
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
  - name: google
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
  - name: facebook
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/facebook.txt
  - name: twitter
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/twitter.txt
  - name: cloudflare
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cloudflare.txt
  - name: netflix
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/netflix.txt
  
stream-domain:      # 域名分流
  #- interface: wan2 # 分流线路
  #  src-addr: 10.1.1.5-10.1.1.254   # 分流的源地址
  #  ## 域名列表网址，每行一个，超过1000行会自动分为多个
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt
  - interface: wan2
    src-addr: 10.1.1.5-10.1.1.254  
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt

  #下面是自动走wan1直连的
  #- interface: wan1
  #  src-addr: 10.1.1.5-10.1.1.254
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
  #- interface: wan1
  #  src-addr: 10.1.1.5-10.1.1.254
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt